services:
  lens-api:
    image: antonwy/lens-gpt-api
    build:
      context: ./lens-gpt-backend
      dockerfile: Dockerfile
    ports:
      - 3002:5000
    restart: always

  frontend:
    image: antonwy/lens-gpt-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    restart: always
    depends_on:
      - lens-api
