services:
  lens-api:
    image: antonwy/lens-gpt-api
    build:
      context: ./lens-gpt-backend
      dockerfile: Dockerfile
    ports:
      - 3002:5000
    command: /bin/bash -c "Xvfb :99 -screen 0 1280x1024x24 & poetry run python -m lens_gpt_backend.main"
    environment:
      - DISPLAY=:99
    restart: always

  frontend:
    image: antonwy/lens-gpt-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    environment:
      - NEXT_PUBLIC_API_URL=http://lens-api:5000
    restart: always
    depends_on:
      - lens-api
